project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)

website:

  title: "Biologia della Conservazione 25/26"
  reader-mode: true
  page-navigation: true
  description: ""
  site-url: https://giulianocolosimo.github.com
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
  
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - text: "Contact"
        href: contact.qmd

  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - section: "Classes"
        title: "Classes"
        contents: 
          - href: ./classes/Conservation Biology 25-26 - Class 1 - Introduction to Conservation Biology.pdf
            text: "Class 1 - Introduction to Conservation Biology"
            icon: file-pdf
          - href: ./classes/Conservation Biology 25-26 - Class 2 - Biodiversity - Concept, Measurement, and Management.pdf
            text: "Class 2 - Biodiversity: Concept, Measurement, and Management"
            icon: file-pdf
          - href: ./classes/Conservation Biology 25-26 - Class 3 - Anthropocene.pdf
            text: "Class 3 - Anthropocene"
            icon: file-pdf
          - href: ./classes/Conservation Biology 25-26 - Class 4 - Populations.pdf
            text: "Class 4 - Populations"
            icon: file-pdf
#          - href: ./classes/5/class_5.html
#            text: "Class 5 - HW and Genetic drift"
#          - href: ./classes/6/class_6.html
#            text: "Class 6 - $N_{e}$ and Population structure"
#          - href: ./classes/7/class_7.html
#            text: "Class 7 - Inbreeding and Inbreeding depression"
#          - href: ./classes/8/class_8.html
#            text: "Class 8 - Hybridization and heritability"
#          - href: ./classes/9/class_9.html
#            text: "Class 9 - Population viability analysis"
#          - href: ./classes/10/class_10.html
#            text: "Class 10 - Conservation and climate change"
#          - href: ./classes/11/class_11.html
#            text: "Class 11 - Excercise: Accessing weather station data"
#          - href: ./classes/12/class_12.html
#            text: "Class 12 - Seminar"
#          - href: ./classes/13/class_13.html
#            text: "Class 13 - Conservation economics 1"
#          - href: ./classes/14/class_14.html
#            text: "Class 14 - GdF seminar"
#          - href: ./classes/15/class_15.html
#            text: "Class 15 - Exercise in R"
#          - href: ./classes/16/class_16.html
#            text: "Class 16 - Conservation economics 2"
#          - href: ./classes/17/class_17.html
#            text: "Class 17 - Conservation technology"



    tools:
      - icon: envelope
        url: "mailto:giuliano.colosimo@protonmail.com"

  page-footer:
    left: "© Copyright 2025 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)."
    background: dark
    

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
