---
title: "Calendar"
author: "Giuliano Colosimo"
editor: visual
date: "2025-09-29"
date-modified: last-modified
bibliography: ./comprehensive_database.bib
csl: ./apa_5th_edition.csl
citation_package: biblatex
citecolor: "red"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
x <- c("calendR",
       "ggthemes",
       "knitr", "kableExtra",
       "lubridate",
       "scales",
       "tidyverse",
       "XML", "xml2")
lapply(x, require, character.only = T)
rm(x)
```

```{r schedule, echo=FALSE}
schedule <- data.frame(" " = c("Lectures", "Mid Term Exam - 1", "Mid Term Exam - 2", "Final exam"),
                       "Day" = c("Mon/Thu", "TBD", "TBD", "TBD"),
                       "Time" = c("14:00-16:00/14:00-16:00", "TBD", "TBD", "TBD"),
                       "Location" = c("Aula centro studi pesca", "Aula centro studi pesca","Aula centro studi pesca", "Aula centro studi pesca"))
kable(schedule, col.names = c(" ", "Day", "Time", "Location"),
      caption = "The course will begin on Monday, September 29, 2025. The tentative schedule for mid-terms and final exams will be updated throughout the course.")
```

<!-- Below you will find a temptative schedule for the rest of the semester and a table with the temptative date for your presentation. Manuscript and dates have been assigned in a random way. Please, if you already know that you will not be present on the date that has been assigned to you let me know in time so that I can arrange a schedule change. -->

::: callout-important
## Read carefully!

It is a student's responsibility to periodically check this website to make sure he/she has the most updated information about the course schedule and content. The dates for the mid term and final exams will be published on this website later during the course of the semester!
:::

```{r}
#| eval: TRUE
#| echo: FALSE

students <- c("Serena Liverino",     "Francesco Baldini",   "Federcio Cornacchia", "Alessia Iacobelli",  
 "Laura Oliva",         "Anna Battista",       "Carlotta Cimini",     "Alessia Caretti",    
 "Leonardo Fritz",      "Lorenzo D'Orfeo",     "Arianna Merli",       "Michela Papa",       
"Chiarta Di Ruzza",    "Ilaria Manni",        "Luca Moruso")


paperAssign <- read.csv("paper assignment.csv", header = T)
ppaperAssign <- read.csv("paper assignment.csv", header = T)
names(paperAssign)<- c("Student", "Title", "Url", "Date")
paperAssign$Student[1:15] <- students
paperAssign$Title <- text_spec(paperAssign$Title,
                               link = paperAssign$Url,
                               format = "html",
                               color = "blue")

kable(paperAssign[, c("Student", "Title", "Date")], 
      format = "html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", 
                                      "condensed", "responsive"),
                font_size = 7)

```

```{r echo=FALSE}
#| out-width: 100%

dates <- seq(as.Date("2025-09-01"), as.Date("2025-09-30"), by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)
events[c(29)] <- "Class"
calendR(month = 9,
        start = "M",
        special.days = events,
        special.col = c("green", "gray"),
        legend.pos = "bottom",
        pdf = F, 
        day.size = 3, 
        weeknames.size = 4, 
        title = "September",
        subtitle="2025",
        text.size = 2.5,              
        text.col = "black",
        text = "14:00-16:00",
        text.pos = 29)
```

```{r echo=FALSE}
#| out-width: 100%

dates <- seq(as.Date("2025-10-01"), as.Date("2025-10-31"), by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)
events[c(2, 6, 9, 13, 16, 20, 23, 27, 30)] <- "Class"
#events[9] <- "Mid Term 1"
calendR(month = 10,
        start = "M",
        special.days = events,
        special.col = c("green", "gray"),
        legend.pos = "bottom",
        pdf = F, 
        day.size = 3, 
        weeknames.size = 4, 
        title = "October",
        subtitle="2025",
        text.size = 2.5,              
        text.col = "black",
        text = "14:00-16:00",
        text.pos = c(2, 6, 9, 13, 16, 20, 23, 27, 30))
```

```{r echo=FALSE}
#| out-width: 100%

dates <- seq(as.Date("2025-11-01"), as.Date("2025-11-30"), by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)
events[c(3, 6, 10, 13, 17, 20, 24, 27)] <- "Class"
calendR(month = 11,
        start = "M",
        special.days = events,
        special.col = c("green", "gray"),
        legend.pos = "bottom",
        pdf = F, 
        day.size = 3, 
        weeknames.size = 4, 
        title = "November",
        subtitle="2025",
        text.size = 2.5,              
        text.col = "black",
        text = "14:00-16:00",
        text.pos = c(3, 6, 10, 13, 17, 20, 24, 27))
```

```{r echo=FALSE}
#| out-width: 100%

dates <- seq(as.Date("2025-12-01"), as.Date("2025-12-31"), by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)
events[c(1,4)] <- "Class"
calendR(month = 12,
        #year = 2025,
        start = "M",
        special.days = events,
        special.col = c("green", "gray"),
        legend.pos = "bottom",
        pdf = F, 
        day.size = 3, 
        weeknames.size = 4, 
        title = "December",
        subtitle="2025",
        text.size = 2.5,              
        text.col = "black",
        text = c("14:00-16:00"),
        text.pos = c(1,4))
```
