---
title: "Biologia della Conservazione"
subtitle: "Evoluzione e Conservazione"
author:
    - name: Giuliano Colosimo
      orcid: 0000-0002-0485-9758
date: "2025-09-29"
date-modified: last-modified
bibliography: ./comprehensive_database.bib
csl: ./apa_5th_edition.csl
citation_package: biblatex
citecolor: "red"
---

# Introduction

Welcome to class! These web-pages contain all the information you need to accomplish your class work for the teaching module **Biologia della Conservazione**. This module is part of the integrated course of Evolution and Conservation.

This is a mandatory module for master level students enrolled in the "Biologia Ambientale" degree at the University of Rome Tor Vergata. It is worth **5 CFU** for a total of 40 hours (i.e., 20 classes of 2 hours each) to be administered in person during the first semester of academic year 2024/2025. The first class will be on Monday, September 29, 2025.

## Program

The module introduces students to Conservation Biology, a synthesis and crisis discipline that uses approaches and methods from disciplines such as Ecology, Population biology, Population genetics, Molecular biology, and applies them to the conservation of species, intended as dynamic entities capable to respond to environmental changes. Criteria and principles for the adoption of the different conservation strategies are presented and discussed throughout the course. Moreover, the practical aspects of the various approaches are examined through the study and analysis of real cases, with particular reference to aspects linked to the research lines carried out and coordinated by the teacher.

Topics covered during the course include: evolutionary genetics of natural populations; loss of genetic variability in small populations; inbreeding and decreased fitness; fragmentation of populations; definition and maintenance of evolutionary potential; population size ($N$ and $N_e$) and its estimators; resolution of taxonomic uncertainties; genetic management of threatened species; adaptation to captivity; planning of head-start interventions and captive-breeding; the IUCN classification; criteria for conservation: species richness, rare species, endemisms; hotspot analysis; gap analysis; climate change; conservation technology; conservation economics.

## Learning objectives

The course aims at providing students with the most fundamental tools to understand, acknowledge, describe, and address problems related to the conservation of Biodiversity. By the end of the course the students should develop autonomy in the process of understanding of different approaches and methods, consolidating the awareness that conservation biology is a crisis discipline that requires specific analytical skills to guide appropriate interventions.

Students are expected to develop professional language and communication skills through a continuous interaction with the teacher and interventions during classes. Additionally, students are guided in the understanding of the discipline through the access to primary literature in English. The process of development such skills is monitored by written periodical checks.


::: callout-note
Attendance is mandatory!
:::

::: callout-important
## Read carefully!

It is a student's responsibility to periodically check this website to make sure he/she has the most updated information about the course schedule and content. The dates for the mid term and final exams will be published on this website later during the course of the semester!
:::


# Pre-requisites

There will be a basic refresher on every single topic discussed throughout the course. Nevertheless, this is a master level course and students participating to this class are expected to have a good grasp of basic concepts in zoology, ecology, population biology, genetics, and molecular biology.

# Course language

The course will be thought in Italian unless international students are present or unless the students express their willingness to learn and participate to the class discussion in English. In this latter case the course will be thought in English. All the material and the literature used (including this website!) will be in English.

# Textbook

There is no mandatory textbook to buy!! While this is true, the overall implant of classes and the material presented is largely sourced from the book Conservation Biology [@VanDyke2020]. All students are expected to attend and take notes during lessons. The material covered in class will be complemented with the scientific literature provided by the professor. Moreover, this website will be periodically updated with new and additional resources that could be useful for the successful completion of this class. 

Below is a BY-NO-MEANS-EXHAUSTIVE list of books and other resources that I strongly encourage you to look at (especially the free material!). This list also includes freely available web applications and/or databases from where it is possible to source and visualize data of interest.

- Introduction to conservation genetics [@Frankham2010]
- [Conservation Biology for all](https://conbio.org/publications/free-textbook), free downloadable book from @Sodhi2010 
- Conservation and the Genomics of Populations [@Allendorf2022]
- [Biology simulation](https://www.biologysimulations.com/population-genetics), a web app to simulate different kind of basic phenomena in biology like the Hardy Weinberg Equilibrium.
- [Binomial Distribution Visualizer](https://shiny.rit.albany.edu/stat/binomial/), a web app developed using R and Shiny to visualize the binomial distribution, a very important type of distribution in conservation genetics.
- [Our World in Data](https://ourworldindata.org), very nice repository with excellent graphical output for some very interesting data sets.


# Meeting hours

Every student is encouraged to contact me by e-mail with questions, doubts, curiosities, and even things you didn't like about this course. My office hours are between 10:00 and 12:00 every Wednesday. My office is number 14, located on the first floor of the main building at "Laboratori di Ecologia Sperimentale ed Acquacoltura" (see the Contact tab for a map with the location of the office). It is always a good idea to e-mail me before coming to the office, to prevent overcrowding :-)

# Students with disabilities

Please, let me know if you require special accommodations to follow this class.

# Diversity, Equity, and Inclusion

The success of this class depends on all of us creating a safe environment where students feel comfortable sharing their thoughts and opinions. We should all strive to be respectful and supportive of one another during class discussions. This class is made better by the contribution of diverse perspectives, and I hope that our class conversations can reflect that.

# References